FROM python:3.10-slim-buster

# Inside Container
# make a new folder inside Container
WORKDIR /backend-flask

# Outside Container -> # Inside Container
# This contain the libraries want to install to run app
COPY requirements.txt requirements.txt

# Inside Container
# install the python libraries used for the app
RUN pip3 install -r requirements.txt

# Outside Container -> # Inside Container
# . mean everythins in the current directory
# first period . - /backend-flask (outside container)
# second period . /backend-flash (inside container)
COPY . .

# Set Environment Variable (Env Vars)
# Inside Container and will remain set when the container is running 
ENV FLASK_ENV=development

EXPOSE ${PORT}

# Cmd (Command)
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]